"""empty message

Revision ID: 958b68687414
Revises: bccad7c0a450
Create Date: 2022-01-22 02:21:02.690339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '958b68687414'
down_revision = 'bccad7c0a450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('results', 'result_all')
    op.drop_column('results', 'url')
    op.drop_column('results', 'result_no_stop_words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('results', 'title')
    # ### end Alembic commands ###
