"""empty message

Revision ID: aa3d4f6d915f
Revises: e5f6b9bdfaf4
Create Date: 2022-01-26 17:37:24.196145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3d4f6d915f'
down_revision = 'e5f6b9bdfaf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cresto_passes', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('cresto_passes', 'symbol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cresto_passes', sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cresto_passes', 'category')
    # ### end Alembic commands ###
