"""empty message

Revision ID: b6c2d56ca144
Revises: aa3d4f6d915f
Create Date: 2022-01-28 18:20:36.725414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c2d56ca144'
down_revision = 'aa3d4f6d915f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cresto_passes', sa.Column('mintedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cresto_passes', 'mintedAt')
    # ### end Alembic commands ###
